set(ASTYLE_INSTDIR ${CMAKE_BINARY_INSTALL_ROOT}/../extnoinstall)

ExternalProject_Add(ASTYLE_BLD
  SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/astyle"
  BUILD_ALWAYS ${EXT_BUILD_ALWAYS} ${LOG_OPTS}
  CMAKE_ARGS
  $<$<NOT:$<BOOL:${CMAKE_CONFIGURATION_TYPES}>>:-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}>
  -DBIN_DIR=${BIN_DIR}
  -DBUILD_STATIC_LIBS=${BUILD_STATIC_LIBS}
  -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
  -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
  -DCMAKE_INSTALL_PREFIX=${ASTYLE_INSTDIR}
  -DCMAKE_INSTALL_RPATH=${CMAKE_BUILD_RPATH}
  -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=${CMAKE_INSTALL_RPATH_USE_LINK_PATH}
  -DCMAKE_SKIP_BUILD_RPATH=${CMAKE_SKIP_BUILD_RPATH}
  -DLIB_DIR=${LIB_DIR}
  LOG_CONFIGURE ${EXT_BUILD_QUIET}
  LOG_BUILD ${EXT_BUILD_QUIET}
  LOG_INSTALL ${EXT_BUILD_QUIET}
  LOG_OUTPUT_ON_FAILURE ${EXT_BUILD_QUIET}
  )

ExternalProject_Add_StepTargets(ASTYLE_BLD install)

SetTargetFolder(ASTYLE_BLD "Third Party Build Tools")

# Local Variables:
# tab-width: 8
# mode: cmake
# indent-tabs-mode: t
# End:
# ex: shiftwidth=2 tabstop=8

